"""add user_id product_name total_price status

Revision ID: 668fa7436ee4
Revises: a6d1931f8dcc
Create Date: 2026-03-07 23:23:24.439828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668fa7436ee4'
down_revision = 'a6d1931f8dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('total_price')
        batch_op.drop_column('product_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
