version: '3.9'

services:

  user-service:
    build: ./services/user-service
    ports:
      - "8001:5000"

  product-service:
    build: ./services/product-service
    ports:
      - "8002:5000"
    volumes:
      - ./services/product-service:/app

  order-service:
    build: ./services/order-service
    ports:
      - "8003:5000"
    depends_on:
      - product-service
      - user-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service