"""add reserved stock

Revision ID: 5d991ecaec26
Revises: f33d07d26e5e
Create Date: 2026-03-24 01:27:41.882519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d991ecaec26'
down_revision = 'f33d07d26e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('reserved_stock')

    # ### end Alembic commands ###
